version: '3'

services:
  php:
    image: progaming/php-oci
    command: /bin/bash
    volumes:
      - .:/var/www/html
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
    working_dir: /var/www/html

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3309:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./docker/init-mysql/ :/docker-entrypoint-initdb.d

  oracle:

    build:
      context: .
      dockerfile: DockerFile-oracle
    ports:
      - "49161:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
